Step 6/6 : RUN pip3 list
 ---> Running in 1a5c225cca50
Package            Version
------------------ -----------
attrs              23.1.0
certifi            2023.5.7
click              8.1.3
click-plugins      1.1.1
cligj              0.7.2
Fiona              1.9.4.post1
geopandas          0.13.2
importlib-metadata 6.7.0
numpy              1.25.0
packaging          23.1
pandas             2.0.2
pip                20.2.4
pyproj             3.6.0
python-dateutil    2.8.2
pytz               2023.3
setuptools         50.3.2
shapely            2.0.1
six                1.16.0
tzdata             2023.3
zipp               3.15.0